[project]
name = "aws-service-authorization-reference"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "asyncio>=3.4.3",
    "httpx>=0.28.1",
    "mcp[cli]>=1.4.1",
    "thefuzz>=0.22.1",
    "typing>=3.10.0.0",
]
